### ISSUE TITLE
Setup Wizard Bugs

### ISSUE THREAD

**Issue by shin-01** [Ansuel/tch-nginx-gui#3]
Setup wizard looks a little buggy,

When i try to use, after setup is complete, on reboot my  router is in bridge mode without a reason

**Comment by Ansuel** [comment]
@shin-01 i think i fixed it... wait a response from you to give you a test gui

**Comment by shin-01** [comment]
Nice, ty. Send it to me,  i'll test it ASAP tomorrow

**Comment by Ansuel** [comment]
@shin-01 

go to the forum repository... you will find GUI_dev.tar.bz2

installa that with the offline buttom.. hope all goes well

i'm here to solve any problem ;)

**Comment by shin-01** [comment]
I've installed the test versione (6.7.7), 
it seems not fixed :(
- Advance settings in broadband is not visible when using ethenet mode
- Using setup wizard to set ADSL (fastweb connection) cause the router to go in bridge mode after reboot. 
-After reboot the broadband mode is VDSL (not ADSL2+), if a select ADSL2+, from advance settings i can set VPI/VCI, but give me error when i click save button. The error is "Alcuni parametri hanno fallito la convalida". It gives the error changing any parameters in broadband section.

If you need any more test, let me know

**Comment by Ansuel** [comment]
Ummm the advanced setting should be visible about the other problem yes I have them too... It's all a mess... I will fix ;)

**Comment by kevdagoat** [comment]
Yep it has been fixed
