### ISSUE TITLE
TG800VAC DHCP Wan Not Connecting

### ISSUE THREAD

**Issue by Townie-au** [Ansuel/tch-nginx-gui#534]
Hi
I have a couple of issues with GUI 8.11.49. Ive been talking kevdagoat. I installed by usin WinSCP method.

I have static internet connection VDSL.
I have a home server with dhcp/dns servers and have a different subnet to the default setting.
Ive found that I can get the internet to connect if I choose fixed ip put all the details in, close the window, then open the window again, switch to dhcp and then back to static and close. Then it will connect, providing I only use the default router address. Also after awhile the internet drops out and I need to do the above again.
I have in the xdsl section "No direct path found" on several driver items.

**Comment by Townie-au** [comment]
7.2.1 firmware too

**Comment by FrancYescO** [comment]
what IP are you setting when putting fixed ip mode and is working? DHCP is provided by the ISP?

**Comment by Townie-au** [comment]
10.40.27.1. DHCP works fine. It received a address, just doesn't connect to the internet for some reason. ISP is like static arp. Give the same address when modem is on DHCP normally.

**Comment by FrancYescO** [comment]
So if you set the same value that the DHCP assign to you in static mode internet is working but not when in DHCP?!

**Comment by Townie-au** [comment]
It does work for awhile and then drops out again but on DHCP nothing. I've left it for ages too, still nothing. Weird ay.

**Comment by Townie-au** [comment]
Any thoughts? I'm going to try putting the isp router mac address in the tg800vac to see of that helps. Other than that not sure. I dunno why the internet drops out when I put static details in. Doesn't drop out with the isp router.

**Comment by FrancYescO** [comment]
probably it drops because the fixed IP you are assigning is not the one that the isp would give to you with DHCP or something like that

do you know what ip is assigning to you when putting the ISP's modem?

the gateway is still pingable from the modem when internet drops? how much is "a while"?

**Comment by Townie-au** [comment]
It's the same. I checked on the isp modem.

Yes I do.

I'm trying that know. I'm having trouble getting it to connect at all now.

What driver should I be using in the xdsl section for tg800vac?

Do I need to install a driver?

**Comment by Townie-au** [comment]
I got it connected. Also managed to change the modem address, disable the dhcp and use my server after the connection was established. If it drops I'll try and ping the isp gateway. 
Firmware version says A2pvfbH043g.d26q
Driver Version says B2pvbH042l (DSL-AC87VG v1.00.10)
I notice there is a TG799VAC version but no TG800VAC.

**Comment by FrancYescO** [comment]
how?

changing the xdsl driver is not needed, but in some circumstance will help getting better stability/sync speed with the DSLAM
799 and 800 have totally different hardware (SoC) so also the driver choices are different

**Comment by Townie-au** [comment]
Ok. 
So it did drop, was unable to ping the gateway.
Then had to get to reconnect by
Internet/Select DHCP/Change connection/Select Static/Change connection

**Comment by FrancYescO** [comment]
have you tried spoofing the original mac address? how much time you can stay online?

**Comment by Townie-au** [comment]
It drops out about every 30mins. 
No. I went to spoof the address but found that option is only available in PPP mode.

**Comment by Townie-au** [comment]
I noticed dyndns is enabled too but can't turn it off. Says invalid ip address and has dropbear command in domain section.

**Comment by Townie-au** [comment]
Thanks for all your help and putting this together btw. Really appreciate it.

**Comment by Townie-au** [comment]
I think even though my isp is giving the same address it's renewing the lease every 30mins.

**Comment by FrancYescO** [comment]
Set MAC address in PPPoE mode it should remain spoofed when going in static/DHCP mode

Dropbear commands in dyndns section i guess is something related on how you got root access on your gateway

Brw what's your ISP? Does it have a public webpage that recap the connection settings?
________________________________

**Comment by Townie-au** [comment]
MyRepublic. It does have a section explaining how to setup 3rd party routers on the NZ site but the Australian one it just states that myrepublic routers are preconfigured to work with their connection and that a 3rd party will not receive any support if it doesn't work. I'll try the mac spoofing.

**Comment by Townie-au** [comment]
No. It doesn't change gateway address.

**Comment by Townie-au** [comment]
Good news.
I downgraded to 16.3 and upgraded gui with the same file used to install it.

I did what you said, went to pop mode and put in the isp modem wan mac address and then changed back to dhcp and then it picked up the ip.

It shouldn't drop out now I don't think.

Thanks a lot, this gui is awesome!

**Comment by kevdagoat** [comment]
Glad you like it and have sorted the problem. 

Will have to mark this as 17.2 compatibility bug

**Comment by Townie-au** [comment]
Looks like it or just my isp blocking the modem and the mac spoofing did it.
Thanks again guys.

**Comment by FrancYescO** [comment]
Thats pretty strange, and still have not clear why you downgraded.

Actually we are showing all xDSL drivers only on >=17.3 Firmwares, but probably 17.2 (or 17.1) is good enought and will help showing/matching the A2pvfbH043g driver in the selectbox when installing it on a TG800

TG799 should be an arm device and it should have a totally different driver versione/list (idk what is the default on this device and it can change olso on different firmwares)

but all of this question about xDSL drivers does not concerne your connectivity issue that is on Layer3

is DHCP mode working after spoofing the MAC?

**Comment by Townie-au** [comment]
I dunno. I downgraded to 16.3 because after spoofing the mac address, dhcp still didn't work. 
The dhcp is working great now with no drops.
The only hiccup I had was the dns servers from the static config caused only the dns to drop when the lease expired and couldn't be removed from the interface. I had to use WinSCP to edit the network config file to remove the listed dns addresses. Then I reboot and picked up the dns addresses as well and it's been great ever since. I could possibly upgrade it to 17.2 again and it might be ok but it's working and don't want to mess with it. The ddns issue was gone to when I flashed 16.3 via the gui also.

**Comment by Townie-au** [comment]
I'll try 17.2 tommorrow just to clear up the real cause of the issue.

**Comment by Townie-au** [comment]
Nope. 17.2 not working. 16.3 worked straight away. The required driver for 17.2 is A2pvfbH043g.d26q.
For some reason the voip isn't trying to register anymore. It's enabled and all my details are but it says na on the status page. Can you's fix that?
I tried mmpbx restart command.

**Comment by FrancYescO** [comment]
Thats pretty strange, we need a comparison btw `/etc/config/network` of 16.3 and 17.1 to go over and get what's wrong

the error you have on `mmpbx` is probably caused due to a misconfiguration, have you used the GUI to change some telephony setting?

`logread -l200 | grep mmpbx` after ~30sec from `/etc/init.d/mmpbxd` restarting should help debugging whats wrong

**Comment by Townie-au** [comment]
Oh man.
The kids are going to kill me. Got 4 kids and the whole house go bizerk when I turn the net off.
My Mrs hates IT related troubleshooting. Doesn't want me to spend the time working stuff out but wants everything to work at all times as well! Haha

I ran these commands as per the rooting guide here...

https://whirlpool.net.au/wiki/hack_technicolor

Could any of these caused issues? Other than that I just added my sip details. Was a mission to get it this stage. The upgrade firmware wasn't working for some reason, with a error code 9. I had to use the PXE flashing method to get it to 16.3. Even a factory reset. Sometimes when I'd try an install gui, I'd get to the Rootdevice force part and it would say command not found but the script was where it should be. 
I noticed there is a update 8.8.55 stable but it's a different file type, can that be applied to this build?

# Block 1
uci delete cwmpd.cwmpd_config
uci delete firewall.cwmpd
uci delete dhcp.hotspot
uci delete dhcp.fonopen
uci delete wifi_doctor_agent.acs
uci delete wifi_doctor_agent.config
uci delete wifi_doctor_agent.as_config
uci delete tls-vsparc.Config
uci delete tls-vsparc.Passive
uci delete autoreset.wifidoctor_enabled
uci delete autoreset.vsparc_enabled
uci delete autoreset.thor_enabled
uci set ddns.myddns_ipv4.enabled='0'
uci set dropbear.wan.enable='0'
uci set dropbear.lan.enable='1'
uci set dropbear.lan.PasswordAuth=on
uci set dropbear.lan.RootPasswordAuth=on
uci add_list web.ruleset_main.rules=iproutesmodal
uci set web.iproutesmodal=rule
uci set web.iproutesmodal.target='/modals/iproutes-modal.lp'
uci add_list web.iproutesmodal.roles='admin'
uci add_list web.ruleset_main.rules=systemmodal
uci set web.systemmodal=rule
uci set web.systemmodal.target='/modals/system-modal.lp'
uci add_list web.systemmodal.roles='admin'
uci add_list web.ruleset_main.rules=relaymodal
uci set web.relaymodal=rule
uci set web.relaymodal.target='/modals/relay-modal.lp'
uci add_list web.relaymodal.roles='admin'
uci add_list web.ruleset_main.rules=natalghelpermodal
uci set web.natalghelpermodal=rule
uci set web.natalghelpermodal.target='/modals/nat-alg-helper-modal.lp'
uci add_list web.natalghelpermodal.roles='admin'

# Block 2
uci add_list web.ruleset_main.rules=diagnosticstcpdumpmodal
uci set web.diagnosticstcpdumpmodal=rule
uci set web.diagnosticstcpdumpmodal.target='/modals/diagnostics-tcpdump-modal.lp'
uci add_list web.diagnosticstcpdumpmodal.roles='admin'
uci set system.config.export_plaintext='1'
uci set system.config.export_unsigned='1'
uci set system.config.import_plaintext='1'
uci set system.config.import_unsigned='1'
uci set web.uidefault.upgradefw_role='admin'
uci add_list web.parentalblock.roles='admin'
uci commit
sed -e 's/session:hasAccess("\/modals\/diagnostics-network-modal.lp")/session:hasAccess("\/modals\/diagnostics-network-modal.lp") and \n session:hasAccess("\/modals\/diagnostics-tcpdump-modal.lp")/' -i /www/cards/009_diagnostics.lp
sed -e 's^alt="network"></div></td></tr>\\^alt="network"></div></td>\\\n <td><div data-toggle="modal" data-remote="modals/diagnostics-tcpdump-modal.lp" data-id="diagnostics-tcpdump-modal"><img href="#" rel="tooltip" data-original-title="TCPDUMP" src="/img/network_sans-32.png" alt="network"></div></td></tr>\\^' -i /www/cards/009_diagnostics.lp
sed -e 's/{"logviewer-modal.lp", T"Log viewer"},/{"logviewer-modal.lp", T"Log viewer"},\n {"diagnostics-tcpdump-modal.lp", T"tcpdump"},\n/' -i /www/snippets/tabs-diagnostics.lp
sed -e 's/if currentuserrole == "guest" /if currentuserrole == "admin" /' -i /www/docroot/modals/gateway-modal.lp
echo > /etc/rc.local
killall -q -9 hotspotd cwmpd cwmpdboot watchdog-tch wifi-doctor-agent tls-vsparc
# Super modders may wish to remove the next line before running.  Most people want it to free up overlay space.
opkg --force-removal-of-dependent-packages remove conf-cwmpd cwmpd autoreset-tch mappings-fon geolocation-tch
find /rom/usr/lib/ipk -type f |xargs -n1 basename | cut -f 1 -d '_' |xargs opkg --force-removal-of-dependent-packages remove
echo > /etc/dropbear/authorized_keys
/etc/init.d/dnsmasq restart
/etc/init.d/nginx restart
/etc/init.d/dropbear start

**Comment by Townie-au** [comment]
I'm pretty sure some of those cleanup commands are interfering with install of gui because when I run those commands, the gui gets an error at the rootdevice command and installs fine without but then cwmp is still enabled and can't be disabled through gui.
Also I think the new version of autogui gives permanent root already by what I have found.
So I'll copy that files you asked for and then flash 7.21 by PXE method and then install gui with only running the cwmp commands and see if the dhcp connects.
How do I attach a file on here?

**Comment by FrancYescO** [comment]
zip or rename in .txt than drag&drop
post here all errors you get on `rootdevice`, run it with de `debug` flag instead of `force`

btw GUI is intended to be installed on a clean system, 90% of these commands are unnedded as installing the GUI you have all options ready to be set

**Comment by Townie-au** [comment]
Ahhh I see but how do I run it on a clean system with no ssh or internet access?

**Comment by FrancYescO** [comment]
i intend clean system as a gateway with only root access gained, 

your wiki is saying
Setting up permanent root access **and other stuff** that

basically for root only these commands are needed:
```
echo root:root | chpasswd
uci set dropbear.lan.enable='1'
uci set dropbear.lan.PasswordAuth=on
uci set dropbear.lan.RootPasswordAuth=on
/etc/init.d/dropbear restart
```

**Comment by Townie-au** [comment]
So I did a factory reset and flashed 1.72.
Then rooted with autogui with no flash.
Then I got the new gui version copied it across with WinSCP.
Then changed ssh password
I only ran the if I command to remove the ddns.
Then ran gui commands, this time with debug.
It's doing what it did before connecting on static but actually no web access from browser, but if I set static, close, then open change dhcp and then back to static. I get web access on the browser. It's connected now, I'll see if it drops out.
I checked the etc/config/network files, they are identical apart from this one says static with all the details of course and the phones working.

**Comment by Townie-au** [comment]
Yeah it dropped again.

**Comment by Townie-au** [comment]
[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/2930423/log.txt)

**Comment by Townie-au** [comment]
[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/2930426/log.txt)

[network-old.txt](https://github.com/Ansuel/tch-nginx-gui/files/2930433/network-old.txt)
[network.txt](https://github.com/Ansuel/tch-nginx-gui/files/2930435/network.txt)

**Comment by Townie-au** [comment]
Thu Feb 28 19:18:48 2019 daemon.warn dnsmasq[3631]: no servers found in /tmp/resolv.conf.hotspot, will retry This anything?

**Comment by FrancYescO** [comment]
try to remove `reqopts` line, than /etc/init.d/network restart

we need to compare 16.3 vs 17.2 configs not dhcp vs static

**Comment by Townie-au** [comment]
Yep will do.
That's is, network old is 16.3 and the other is 17.2.

**Comment by FrancYescO** [comment]
but network old is configured in static mode, the best is to compare same connection mode... but also looking at this comparison i guess there will be not too much differences probably the issue is somewhere else :/

using latest dev version the xdsl driver selected in the dropdown is corresponding to the firmware version? are xdsl firmware changing btw 16.3 and 17.2 ?

and probably @kevdagoat or @flywire can help in this is somewhere an extracted 16.3 firmware?

actually i should have an extracted
vant-y_CRF779-17.2.0213-820-RB

looking at this page there are other 3 fw available for TG800 (and idk what of the 3 17.2 you are using)
https://bc.whirlpool.net.au/bc/hardware/?action=h_view&model_id=1622

**Comment by Townie-au** [comment]
I'm using 17.2.0261-820-RA and 16.3.7567-660-RD.
The gui ver is 8.8.55.

Yes the firmware does change but only when use PXE method, if I try with autogui I get authorization error for some reason. Haven't tried with the new gui yet.

**Comment by FrancYescO** [comment]
8.8.55 ?! thats pretty old! use the latest dev or at least stable

**Comment by Townie-au** [comment]
But it says flashing dev will brick my device.

**Comment by Townie-au** [comment]
That is the latest stable isn't it?

**Comment by Townie-au** [comment]
Awww man. That hacking guide is out of date and the requred driver is in the repository!
Can I use creat_zip.bat to run initialize_gui.sh to install gui without using autogui to root it first?

**Comment by Townie-au** [comment]
And is the dev version safe to use?

**Comment by kevdagoat** [comment]
Yes on a tg800, you have 512mbyte flash vs 128

**Comment by Townie-au** [comment]
What's cui validation missing for peerdns?

**Comment by Townie-au** [comment]
Ok.
I installed the latest version gui_dev and the xdsl driver matches but still no wan connection.
You guys see anything off in the files?
[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/2935165/log.txt)
[messages.log](https://github.com/Ansuel/tch-nginx-gui/files/2935168/messages.log)

**Comment by Townie-au** [comment]
Also get "Validation missing for uci_wan_peerdns" when trying to set wan spoof address.

**Comment by Townie-au** [comment]
I can't get turn off pppoe relay either.

**Comment by Townie-au** [comment]
When I try and set static, it says saved successfully but the card says static disabled.

**Comment by Townie-au** [comment]
If I set to static and put no end, does this set dns to auto? If yes, didn't work. If no, please tell. 
I noticed in the isp modem that's how it was set.
I know dhcp should work like before but this could be a workaround.

**Comment by Townie-au** [comment]
Is there a way I can use a script to get the modem to request a wan address?

**Comment by Townie-au** [comment]
How do I fix
Validation missing for uci_wan_peerdns?

**Comment by Townie-au** [comment]
I'm going load 16.3 with gui 8.11.49 into bank 2 and 17.2 with the latest gui_dev and compare the config files.
I noticed I'm getting a lot of dnsmasq can't open listen port on 53 and when I check ngisk is using it.
I notice not any comments. Have I outstayed my welcome? :(

**Comment by FrancYescO** [comment]
> Validation missing for uci_wan_peerdns?

should be fixed in latest dev

> I noticed I'm getting a lot of dnsmasq can't open listen port on 53 and when I check ngisk is using it.

nginx is using port 53? O.o 

> Also dhcp config says modem gateway address not my server 2012 dhcp and dns address.

So you don't use the modem dns "proxy" dns server but a custom dns server by your server? i think this should be easily changed by assigning a differente DNS to lan clients, while on the WAN side there is another func to not use the provided dns in the internet modal (on latest dev)

**Comment by Townie-au** [comment]
The latest release fixed the peerdns and nginx is no longer using port 53.
However there is still
dnsmasq: failed to create listening socket for port 53: Address already in use
When I check there is only dnsmasq using it, as it's supposed too.
I'll get this 16.3 and 17.2 going and post what I find.

**Comment by FrancYescO** [comment]
Probably something about ipv4/v6 that is trying to bind port 53 2 times
________________________________

**Comment by Townie-au** [comment]
I set it up, and worked straight away on 16.3. I've been looking at the config files, that look the same. There's no port 53 blocked error. Thinking something to do dnsmasq and/or the dhcp scripts that control the request of ip address from wan and the lan, but you know over my head.

**Comment by Townie-au** [comment]
So on the latest gui dev with 16.3 the blocked dns port still persists, downgrading to the latest stable solves the problem. I set the wan spoof manually with the option macadd line.
I also noticed even though set to dhcp the config was in atm mode. I had to change to adsl2 then back to dhcp and the internet connected.

**Comment by Townie-au** [comment]
Can I browse the config files in the passive bank via WinSCP?

**Comment by FrancYescO** [comment]
/overlay/nameofthepassivebank

**Comment by Townie-au** [comment]
Can I install gui on both banks?

**Comment by Townie-au** [comment]
It just says bank_1 and the files are the files in the active firmware. No bank_2 but gui confirms bank_2 has 17.2. Is there a way to extract the rbi file from 17.2?

**Comment by FrancYescO** [comment]
if no /overlay/bank_2 folder, means the bank_2 is just not configured/never booted

you should have enough space to install GUI on both banks if device is with more than 32mb of flash, remember that with bank check flag setted in gui>extra, bank_1 is always forced

**Comment by kevdagoat** [comment]
Ok to close?

**Comment by kevdagoat** [comment]
Advice: Stay with 16.3

**Comment by Townie-au** [comment]
Yep, sorry.
I found for some reason even with stock rooted 17.2 dhcp doesn't work with my isp but 16.3 does. Nothing to do with GUI so yep close it kev

**Comment by kevdagoat** [comment]
You have to :)

I don’t have collaborator access :(
