### ISSUE TITLE
Changed the default gui to fritz now picking cards wont load

### ISSUE THREAD

**Issue by evox225** [Ansuel/tch-nginx-gui#811]
i have changed to fritz gui now when i choose cards it just says loading and stays on that

**Comment by evox225** [comment]
here is a picture of the issue https://imgur.com/a/A6G831m

**Comment by evox225** [comment]
is there anyway to reset the gui layout back to default via ssh or something?

**Comment by FrancYescO** [comment]
GUI version and firmware missing.
`uci set modgui.gui.gui_skin='green'`

**Comment by evox225** [comment]
> GUI version and firmware missing.
> `uci set modgui.gui.gui_skin='green'`

thanks for the reply the skin has reset and is now back to default again thanks. i provided a picture in a comment from the first one with the gui version & firmware

**Comment by FrancYescO** [comment]
ok the issue should be already solved in the latest dev version.

**Comment by prasadsw** [comment]
I had the same issue as @evox225 changed to Fritzbox and was never able to get back to regular layout. This was most frustrating and what drove me to backout; Are there any other scripts that allow us to change params if we can't get to the UI other than upgradeui - which did not correct the fritzbox selection...

**Comment by evox225** [comment]
> I had the same issue as @evox225 changed to Fritzbox and was never able to get back to regular layout. This was most frustrating and what drove me to backout of DEV; Are there any other scripts that allow us to change params if we can't get to the UI other than upgradeui - which did not correct the fritzbox selection...

SSH into the router and input this: uci set modgui.gui.gui_skin='green'

That will default back to the stock skin. Thanks to FrancYesc0 for that above

**Comment by Kwbmm** [comment]
Hello,
I am experiencing the same issue. `uci set modgui.gui.gui_skin='green'` fixes the problem, but then, from the UI it is not possible to change back to fritz skin. When selecting a fritzbox skin, in the option `GUI first page` I can only select stats and when I click `save` changes are not persisted.

**Comment by milouk** [comment]
This issue still exists in 9.6.65-89342d7b. Id recommend re-opening this issue

**Comment by SushiTee** [comment]
This issue still exists with 9.6.95-7735860f. I'm on AGTHP_2.3.3 Please reopen the issue.

This is what the the nginx error log shows:

`2022/04/30 19:32:09 [error] 6023#0: *6 lua entry thread aborted: runtime error: [string "001_system-info.lp"]:12: module 'variant_helper' not found:
        no field package.preload['variant_helper']
        no file './variant_helper.lua'
        no file '/usr/share/lua/variant_helper.lua'
        no file '/usr/share/lua/variant_helper/init.lua'
        no file '/usr/lib/lua/variant_helper.lua'
        no file '/usr/lib/lua/variant_helper/init.lua'
        no file '/usr/lib/lua/variant_helper.lua'
        no file '/www/lua/variant_helper.lua'
        no file '/usr/lib/lua/variant_helper.so'
stack traceback:
coroutine 0:
        [C]: in function 'require'
        [string "001_system-info.lp"]:12: in function 'content'
        /usr/lib/lua/web/lp.lua:176: in function 'include'
        [string "cards.lp"]:59: in function 'content'
        /usr/lib/lua/web/lp.lua:176: in function 'include'
        [string "/cards.lp"]:27: in function 'content'
        /usr/lib/lua/web/web.lua:268: in function 'process'
        content_by_lua(nginx.conf:108):4: in function <content_by_lua(nginx.conf:108):1>, client: 192.168.178.202, server: localhost, request: "GET /cards.lp HTTP/1.1", host: "192.168.178.1", referrer: "http://192.168.178.1/cards.lp"
`
