### ISSUE TITLE
Add more checks before installing app when using device offline

### ISSUE THREAD

**Issue by aetonsi** [Ansuel/tch-nginx-gui#908]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
i have not found the "system extras" card

#### Device Model
DGA4132 Version Cobalt (18.3.k)

#### Gui Version
9.5.17-5b723682

#### Description of problem
Console commands executed in the web UI are not shown.
If i try to " Install Specific App Online" or if i try to install "extensions" (aria2, transmission, etc), a black line is show and a javascript error pops up. Reloading the page shows that the requested operation has completed successfully, though.
Browser version:  Chromium 80, chrome 80

#### How to reproduce (if possible)
Just install some extension.

#### Media/Photos (if possible)
error + demo that the command completed correctly (or so it seems):
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18366087/77228981-54780780-6b8b-11ea-8a40-2f742e875faa.gif)

error in hd:
![image](https://user-images.githubusercontent.com/18366087/77228996-69ed3180-6b8b-11ea-8400-5e2eda2097db.png)

**Comment by FrancYescO** [comment]
should be already fixed in dev.

**Comment by aetonsi** [comment]
@FrancYescO 
> should be already fixed in dev.

in dev, this happens:
![ezgif-1-45b859d7327d](https://user-images.githubusercontent.com/18366087/77236978-fca9c280-6bc3-11ea-9444-0e267790ddce.gif)

and it doesn't seem to stop... then i have to reload the page manually.
is it correct?

**Comment by aetonsi** [comment]
Ok, what is shown here https://github.com/Ansuel/tch-nginx-gui/issues/908#issuecomment-602107952 happens when you don't have an active connection: it shows no warning about the absence of connection, and when you reload the page it shows that the web extensions are somehow correctly installed. I think this may be a different bug..

Also, repeating the steps with internet connection, the following message is shown at the end of the operation:
![image](https://user-images.githubusercontent.com/18366087/77238841-44384a80-6bd4-11ea-9e03-531262db01af.png)
Is it correct?
After reloading the page, it shows that "Specific App are already Installed", but i can't trust it at this point.. how can i check if it worked?

Also, a sidenote: what does the "Specific App" installation do? i've been using it to test the web ui console commands but i don't even know what is it for

**Comment by aetonsi** [comment]
Update
i just tried to install 'luci' (with internet connection this time): it errored out every command, but it still shows that it's installed. This is the output:
```
Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base/Packages.gz
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/packages/Packages.gz
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/packages/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/luci/Packages.gz
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/luci/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/routing/Packages.gz
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/routing/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/telephony/Packages.gz
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/telephony/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/target/packages/Packages.gz
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/target/packages/Packages.gz

Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VANTW/packages/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VANTW/packages/Packages.gz

No packages removed.
Unknown package 'libuci-lua'.
Unknown package 'luci'.
Unknown package 'rpcd'.
h/VANTW/packages/Packages.gz, wget returned 1.
Collected errors:
 * opkg_install_cmd: Cannot install package libuci-lua.
 * opkg_install_cmd: Cannot install package luci.
 * opkg_install_cmd: Cannot install package rpcd.
mv: can't rename '/www/cgi-bin': No such file or directory
mv: can't rename '/www/luci-static': No such file or directory
mv: can't rename '/www/index.html': No such file or directory
rm: can't remove '/usr/lib/lua/uci.so': No such file or directory
sed: /usr/lib/lua/luci/model/uci.lua: No such file or directory
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
/usr/share/transformer/scripts/appInstallRemoveUtility.sh: line 430: /etc/init.d/uhttpd: not found
```
And this is the result if i reload the page:
![image](https://user-images.githubusercontent.com/18366087/77238955-a34a8f00-6bd5-11ea-814e-e5a22995bdae.png)
Obviously, it doesn't work...

I might have something completely broken in my installation, i think, at this point... i will "Reset to Factory" then try everything again.

I'll update you.

**Comment by FrancYescO** [comment]
yeah lot of things got not tested without internet connection, thats why you are having these strange behaviours

you can just retry uninstalling and than reinstalling luci, this requires that specific package is already installed and internet working before starting the installation

**Comment by aetonsi** [comment]
Hi again, i have installed v9.5.38 and i just installed (**successfully** this time!) luci and aria2, but still the "console" web ui broke again as it did **before** v9.5.35: there might be a regression...
here's a screenshot:
![image](https://user-images.githubusercontent.com/18366087/78462056-e07f4880-76ce-11ea-8975-4b0d5d7cbb2c.png)

have a nice day

**Comment by FrancYescO** [comment]
the 2nd js error should be solved in https://github.com/Ansuel/tch-nginx-gui/commit/de2d7bab30271fb877e183d193205f25a35c7c66

idk what is the first one from polyfill (?)

**Comment by aetonsi** [comment]
I checked and the polyfill thing is a broken extension, so don't worry about it.
I just checked with https://github.com/Ansuel/tch-nginx-gui/commit/de2d7bab30271fb877e183d193205f25a35c7c66 and i can confirm it works perfectly:

![image](https://user-images.githubusercontent.com/18366087/78473350-3809cc80-7740-11ea-9584-39d6b9e78da9.png)


I'm closing the issue,
thanks,
have a nice day
