### ISSUE TITLE
GUI 9.5.80: tiles "schede" "statistiche" don't work

### ISSUE THREAD

**Issue by boynet7000** [Ansuel/tch-nginx-gui#963]
Device Model: Technicolor TG789VAC v2
Gui Version: 9.5.80

Description of problem + how to reproduce:
problem started after upgrading from previous dev GUI (v.75?)

after log in, pressing on tile "schede" doesn't produce any effect. (hangs1.jpg)
"traffico internet" stay empty

You can reach "cards" directly, i.e. wirting URL http://IP_MODEM/cards.lp in browsers' address bar
In this case pressing tile "statistiche" causes modem to hang (hangs2.jpg)

p.s: 5ghz analyzer still doesn't find any network (ref. other bug I opened weeks ago)

![hangs1](https://user-images.githubusercontent.com/47531173/82590952-dfcb4480-9b9e-11ea-8b01-116759c4bd6d.jpg)
![hangs2](https://user-images.githubusercontent.com/47531173/82590956-e1950800-9b9e-11ea-80c2-a50fccc581f9.jpg)
[DebugHelper2020-05-21-2003.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4663998/DebugHelper2020-05-21-2003.tar.gz)

**Comment by FrancYescO** [comment]
could you explain you actual network configuration? did VDSL was connected and than disconnected?

**Comment by FrancYescO** [comment]
check if it is fixed with 9.5.81

**Comment by boynet7000** [comment]
downloaded v9.5.82 but it is not fixed. Also tile "aggiorna" in "statistiche" doesn't work.

VDSL is not used as modem connect via ethernet using wan port in bridge mode

**Comment by FrancYescO** [comment]
result of `transformer-cli get sys.class.xdsl.@line0.DownstreamCurrRate`

**Comment by boynet7000** [comment]
here it is:
ERROR   get(sys.class.xdsl.@., DownstreamCurrRate) failed: /usr/lib/lua/transformer/shared/xdslctl.lua:546: attempt to call field 'getMinimalDSLStatistics' (a nil value)
stack traceback:
        /usr/lib/lua/transformer/shared/xdslctl.lua:546: in function 'getMinimalDSLStatistics'
        /usr/lib/lua/transformer/shared/xdslctl.lua:730: in function </usr/lib/lua/transformer/shared/xdslctl.lua:724>
        (tail call): ?
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/lib/lua/transformer/navigation.lua:169: in function 'get_parameter_value'
        /usr/lib/lua/transformer/navigation.lua:207: in function 'get'
        /usr/lib/lua/transformer/api.lua:190: in function </usr/lib/lua/transformer/api.lua:181>
        [C]: in function 'pcall'
        /usr/lib/lua/transformer/api.lua:36: in function 'do_pcall'
        /usr/lib/lua/transformer/api.lua:88: in function </usr/lib/lua/transformer/api.lua:86>
        (tail call): ?
        /usr/bin/transformer:178: in function '?'
        /usr/bin/transformer:454: in function </usr/bin/transformer:437>
        [C]: in function 'pcall'
        /usr/bin/transformer:477: in function </usr/bin/transformer:460>
        [C]: in function 'run'
        /usr/bin/transformer:500: in function </usr/bin/transformer:488>
        [C]: in function 'pcall'
        /usr/bin/transformer:511: in main chunk
        [C]: ?

**Comment by realindiahotel** [comment]
@FrancYescO also I have this problem! 9.5.82 and when I log in if I select "Cards" it just hangs and does nothing. I can navigate to the URL /cards.lp directly. Also when on cards if I select "Stats" it also just hangs and doesn't take me to the stats page.

On top of this it does not report my xDSL statistics so it is saying 0 values for upstream and doenstream so I can no longer see my sync speed.

MediaAccess TG ( MediaAccess TG789MYRvac v2 HP )

**Comment by boynet7000** [comment]
found v9.5.83: problem still present

**Comment by realindiahotel** [comment]
Problem also remains for me on 9.5.83

**Comment by realindiahotel** [comment]
[DebugHelper2020-05-23-0016.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4668661/DebugHelper2020-05-23-0016.tar.gz)

@FrancYescO here is my debug log

**Comment by boynet7000** [comment]
@realindiahotel twice is not enough in my modem... :-)

this time debug worked also for me...

[DebugHelper2020-05-22-1607.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4668673/DebugHelper2020-05-22-1607.tar.gz)

**Comment by realindiahotel** [comment]
> result of `transformer-cli get sys.class.xdsl.@line0.DownstreamCurrRate`

root@TG789MYRvac:~# transformer-cli get sys.class.xdsl.@line0.DownstreamCurrRate
ERROR	get(sys.class.xdsl.@., DownstreamCurrRate) failed: /usr/lib/lua/transformer/shared/xdslctl.lua:546: attempt to call field 'getMinimalDSLStatistics' (a nil value)
stack traceback:
	/usr/lib/lua/transformer/shared/xdslctl.lua:546: in function 'getMinimalDSLStatistics'
	/usr/lib/lua/transformer/shared/xdslctl.lua:730: in function </usr/lib/lua/transformer/shared/xdslctl.lua:724>
	(tail call): ?
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/lib/lua/transformer/navigation.lua:157: in function 'get_parameter_value'
	/usr/lib/lua/transformer/navigation.lua:195: in function 'get'
	/usr/lib/lua/transformer/api.lua:105: in function </usr/lib/lua/transformer/api.lua:101>
	[C]: in function 'pcall'
	/usr/lib/lua/transformer/api.lua:24: in function 'do_pcall'
	/usr/lib/lua/transformer/api.lua:77: in function </usr/lib/lua/transformer/api.lua:75>
	(tail call): ?
	/usr/bin/transformer:124: in function '?'
	/usr/bin/transformer:366: in function </usr/bin/transformer:350>
	[C]: in function 'pcall'
	/usr/bin/transformer:389: in function </usr/bin/transformer:372>
	[C]: in function 'run'
	/usr/bin/transformer:412: in function </usr/bin/transformer:400>
	[C]: in function 'pcall'
	/usr/bin/transformer:423: in main chunk
	[C]: ?

**Comment by FrancYescO** [comment]
check if 
`curl -k https://raw.githubusercontent.com/FrancYescO/tch_firmware_extracted/AGTEF_2.2.0_CLOSED/usr/lib/lua/luabcm.so -o /usr/lib/lua/luabcm.so` fix the issue

**Comment by realindiahotel** [comment]
> check if
> `curl -k https://raw.githubusercontent.com/FrancYescO/tch_firmware_extracted/AGTEF_2.2.0_CLOSED/usr/lib/lua/luabcm.so -o /usr/lib/lua/luabcm.so` fix the issue

Problem persists after applying that and reboot.

Now if I run > transformer-cli get sys.class.xdsl.@line0.DownstreamCurrRate

I have a different error suggesting an incorrect path or something?

root@TG789MYRvac:~# transformer-cli get sys.class.xdsl.@line0.DownstreamCurrRate
ERROR	invalid path sys.class.xdsl.@.

**Comment by boynet7000** [comment]
@FrancYescO
befor trying, I have a doubt:  AGTEF_2.2.0 is another name for Technicolor TG789VAC v2?
And... can You please post a link to downolad latest version prior v80? was it v75?

**Comment by FrancYescO** [comment]
please confirm it is fixed

**Comment by realindiahotel** [comment]
> please confirm it is fixed

Nothing you said worked. I updated to 9.5.84 and it is even more broken than before, now it shows this error message in xDSL area 
![image](https://user-images.githubusercontent.com/2297007/82697372-23f83b00-9cac-11ea-8a54-8f59a8856c7c.png)

NOT FIXED

**Comment by FrancYescO** [comment]
restore your .so file 

`cp /rom/usr/lib/lua/luabcm.so /usr/lib/lua/luabcm.so`

**Comment by realindiahotel** [comment]
> restore your .so file

Yep ok so restored .so as you said and I also then ran sudo upgradegui to do a fresh copy of the update and it is working now in .84 thanks.

**Comment by boynet7000** [comment]
I couldn't resist till monday... :-)
Found v.84 and installed: bug fixed also in my case.
Thanks for Your quick assistance!

**Comment by realindiahotel** [comment]
@FrancYescO after some time the "Cards" and "Stats" buttons have stopped working again for me again. However the xDSL stats are being reported. v9.5.84

**Comment by FrancYescO** [comment]
post same command as before and a logread/debug zip

**Comment by boynet7000** [comment]
tried now: tiles and stats works.
Here is my "debug" to help
[DebugHelper2020-05-25-0935.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4675837/DebugHelper2020-05-25-0935.tar.gz)
